server:
  port: 1008

spring:
  application:
    name: xiaoyu-admin


  cloud:
    consul:
      port: 8900
      discovery:
        tags: user.name=xiaoyu,user.password=1234

  security:
    user:
      name: xiaoyu
      password: 1234

  boot:
    admin:
      discovery:
        ignored-services: consul



management:
  endpoints:
    web:
      exposure:
        include: "*"
