server:
  port: 2000

spring:
  application:
    name: xiaoyu-config

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kinun0623/springcloud-config
          search-paths: respo
      label: master

    consul:
      port: 8900
