server:
  port: 1000

spring:
  application:
    name: xiaoyu-service

  cloud:
    consul:
      port: 8900

  zipkin:
    base-url: http://localhost:1005

  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "*"
